apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ethmur/tms_backend:latest
        ports:
        - containerPort: 8080
        env:
          - name: DB_ENDPOINT
            value: {{DB_ENDPOINT}}
          - name: DB_USERNAME
            value: {{DB_USERNAME}}
          - name: DB_PASSWORD
            value: {{DB_PASSWORD}}
