all:
  hosts:
    jenkins_server:
        ansible_host: "{{ jenkins_server_hostname }}"
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "{{ private_key_filepath }}"
    ansible_ssh_extra_args: -o StrictHostKeyChecking=no
    ansible_python_interpreter: /usr/bin/python3
