CREATE DATABASE IF NOT EXISTS tms;
CREATE TABLE IF NOT EXISTS tms.ticket(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	description VARCHAR(100) NOT NULL,
	author VARCHAR(100) NOT NULL,
	status VARCHAR(100) NOT NULL,
	time_created DATETIME NOT NULL
);
